name: it-with-arq-wildfly-remote

on:
  push:
    paths-ignore:
      - "docs/**"
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  it-with-arq-wildfly-remote:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "21"
      - run: java -version

      - name: Run integration test with -Parq-wildfly-remote
        run: mvn clean verify -Parq-wildfly-remote
